# Generated by Django 2.2.3 on 2019-09-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190923_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='pname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=200, verbose_name='Product Family'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=200, verbose_name='SKU'),
        ),
    ]
