# Generated by Django 2.2.3 on 2019-09-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190923_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='ProductFamily',
            new_name='product_family',
        ),
    ]
