# Generated by Django 2.2.3 on 2019-09-23 05:45

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190923_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path)),
                ('product', models.ForeignKey(default=None, on_delete='CASCADE', to='product.Product')),
            ],
        ),
    ]
