# Generated by Django 2.2.3 on 2019-09-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190923_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='op_value',
            field=models.BooleanField(default=False),
        ),
    ]
