# Generated by Django 2.2.3 on 2019-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190923_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='options',
            field=models.ManyToManyField(to='product.ProductOption'),
        ),
    ]
