# Generated by Django 2.2.3 on 2019-09-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190923_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_images',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Image'),
        ),
    ]
