# Generated by Django 2.2.3 on 2019-09-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190923_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product'),
        ),
    ]
