# Generated by Django 2.2.3 on 2019-09-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productvariant_featuredimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='featuredimage',
        ),
    ]
