# Generated by Django 2.2.3 on 2019-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_category',
            field=models.ManyToManyField(to='product.Category'),
        ),
    ]
