# Generated by Django 2.2.3 on 2019-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productvariant_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
