# Generated by Django 2.2.6 on 2019-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
