# Generated by Django 2.2.3 on 2019-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='product.ProductVariant'),
        ),
    ]
